---

zabbix_installation_method:             repo
zabbix_repo_to_add:                     True

zabbix_version_major:       "7.2"

zabbix_repo_release: "{{ ansible_distribution_release }}"

zabbix_repo_by_os:
  Ubuntu: "deb https://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/ubuntu {{ zabbix_repo_release }} main"
  Debian: "deb https://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/debian {{ zabbix_repo_release }} main"

zabbix_repo: "{{ zabbix_repo_by_os[ansible_distribution] | default('') }}"

ansible_required_package_by_os:
  Ubuntu:       []
  Debian:       []
  RedHat:
    - libselinux-python
  CentOS:
    - libselinux-python

ansible_required_package:  "{{ ansible_required_package_by_os[ ansible_distribution ] | default('none') }}"