---
# ----------------------------------------------------------------------
#                           Zabbix Installation
# ----------------------------------------------------------------------

- hosts: zabbix-server
  roles:
    - { role: mariadb, when: not ci_testing | default(false) }
    - { role: zabbix-repository, when: not ci_testing | default(false), tags: [ server, agent ] }
    - { role: zabbix-server, when: not ci_testing | default(false), tags: server }
    - { role: zabbix-client, when: not ci_testing | default(false), tags: agent }
    - ansible-pull
    - user-management
    - { role: verify-services, when: not ci_testing | default(false) }

- hosts: zabbix-proxy
  roles:
    - { role: mariadb, when: not ci_testing | default(false) }
    - { role: zabbix-repository, when: not ci_testing | default(false) }
    - { role: zabbix-proxy, when: not ci_testing | default(false) }
    - { role: zabbix-client, when: not ci_testing | default(false) }
    - ansible-pull
    - user-management
    - { role: verify-services, when: not ci_testing | default(false) }

- hosts: zabbix-client
  roles:
    - { role: zabbix-repository, when: not ci_testing | default(false) }
    - { role: zabbix-client, when: not ci_testing | default(false) }
    - ansible-pull
    - user-management
    - { role: verify-services, when: not ci_testing | default(false) }

# ----------------------------------------------------------------------
# eof
