---
# ----------------------------------------------------------------------
#                           Zabbix Installation
# ----------------------------------------------------------------------

- hosts: zabbix-server
  roles:
    - mariadb
    - { role: zabbix-repository, tags: [ server, agent ] }
    - { role: zabbix-server, tags: server }
    - { role: zabbix-client, tags: agent }
    - ansible-pull
    - user-management
    - verify-services

- hosts: zabbix-proxy
  roles:
    - mariadb
    - zabbix-repository
    - zabbix-proxy
    - zabbix-client
    - ansible-pull
    - user-management
    - verify-services

- hosts: zabbix-client
  roles:
    - zabbix-repository
    - zabbix-client
    - ansible-pull
    - user-management
    - verify-services

# ----------------------------------------------------------------------
# eof
