---
- name: restart zabbix proxy
  become: yes
  service:
    name: zabbix-proxy
    state: restarted

- name: restart zabbix agent
  become: yes
  service:
    name: zabbix-agent
    state: restarted
