---
- name: Add Zabbix apt key
  apt_key:
    url: "{{ zabbix_key_url }}"
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: "{{ zabbix_apt_repo }}"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zabbix proxy package
  apt:
    name: zabbix-proxy-mysql
    state: present

- name: Configure Zabbix proxy
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
  notify: Restart Zabbix proxy

- name: Ensure Zabbix proxy service
  service:
    name: zabbix-proxy
    state: started
    enabled: yes
