---
# Install Zabbix agent from yum repo repository

# -------------------------------------------------------------
#  remove stale version

- name: remove stale Zabbix server
  become: yes
  yum: name={{ item }} state=absent
  with_items: "{{ zabbix_packages }}"
  when: zabbix_remove_stale_version | bool

- name: remove stale files from previous installation (if any)
  become: yes
  file: name="{{ item }}" state=absent
  with_items: "{{ zabbix_stale_files }}"
  when: zabbix_remove_stale_version | bool

# -------------------------------------------------------------
#  install new package

- name: install Zabbix server packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ zabbix_packages }}"
  notify:
    - enable zabbix server
    - start zabbix server
