---
- name: Install pip on RedHat
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install pip on Debian
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
     
- name: Install python expect
  pip:
    name: pexpect

- name: Open Firewall
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  with_items:
    - '{{service_ports}}'
  ignore_errors: true
