---
# Zabbix Official package repository

# -------------------------------------------------------------
#  2. add repository configuration

- name: add Zabbix Ubuntu repository signing key
  become: yes
  apt_key:
    data: "{{ lookup('file', 'zabbix.pgp') }}"
    state: present
  when: "{{ zabbix_repo_to_add }}"

- name: configure Zabbix APT repository
  become: yes
  apt_repository:
    repo: "{{ zabbix_repo }}"
    filename: zabbix
    state: present
  when: "{{ zabbix_repo_to_add }}"
  register: zabbix_repo_config_added

- name: update package data
  become: yes
  apt:
    update_cache: yes
  when: zabbix_repo_config_added.changed
