---
# Zabbix Official package repository

# -------------------------------------------------------------
#  2. add repository configuration

- name: download Zabbix GPG key
  become: yes
  get_url:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    dest: /tmp/zabbix.asc
    mode: '0644'
  when: zabbix_repo_to_add

- name: dearmor Zabbix key
  become: yes
  command: gpg --dearmor -o /usr/share/keyrings/zabbix.gpg /tmp/zabbix.asc
  args:
    creates: /usr/share/keyrings/zabbix.gpg
  when: zabbix_repo_to_add

- name: configure Zabbix APT repository
  become: yes
  apt_repository:
    repo: "{{ zabbix_repo }}"
    filename: zabbix
    state: present
  when: zabbix_repo_to_add
  register: zabbix_repo_config_added

- name: update package data
  become: yes
  apt:
    update_cache: yes
  when: zabbix_repo_config_added.changed
