---
# Zabbix Official package repository

# -------------------------------------------------------------
#  2. install package with Zabbix repo configuration

- name: add Zabbix Ubuntu repository signing key
  become: yes
  apt_key: data="{{ lookup('file', 'zabbix.pgp') }}" state=present
  when: "{{ zabbix_repo_to_add }}"

- name: ensure Zabbix apt repository is configured
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/ubuntu {{ zabbix_repo_release }} main"
    filename: zabbix
    state: present
  when: zabbix_repo_to_add

- name: update package data
  become: yes
  apt: update_cache=yes
  when: zabbix_repo_to_add
