---
- name: create ansible-pull script
  become: yes
  copy:
    dest: /usr/local/bin/run-ansible-pull.sh
    mode: '0755'
    content: |
      #!/bin/bash
      ansible-pull -U {{ ansible_pull_repo }} -C {{ ansible_pull_branch }}

- name: create systemd unit
  become: yes
  copy:
    dest: /etc/systemd/system/ansible-pull.service
    content: |
      [Unit]
      Description=Run ansible-pull

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/run-ansible-pull.sh

- name: create systemd timer
  become: yes
  copy:
    dest: /etc/systemd/system/ansible-pull.timer
    content: |
      [Unit]
      Description=Run ansible-pull every {{ ansible_pull_frequency }}

      [Timer]
      OnBootSec=5min
      OnUnitActiveSec={{ ansible_pull_frequency }}

      [Install]
      WantedBy=timers.target

- name: enable and start ansible-pull timer
  become: yes
  systemd:
    name: ansible-pull.timer
    enabled: yes
    state: started
